name: eletrofrio-ai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - ipykernel
  - sqlalchemy
  - psycopg2
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - python-dotenv
      - pydantic
      - requests
