from __future__ import annotations

from typing import Any


DEFAULT_OPERATIONAL_RULES: list[dict[str, Any]] = [
    {
        "name": "Alta temperatura em congelados",
        "description": "Protege equipamentos de congelados contra operação acima do limite esperado.",
        "scope_type": "equipment_type",
        "scope_value": "frozen",
        "priority": 10,
        "severity_when_triggered": "critical",
        "equipment_type": "frozen",
        "measurement_type": "temperature",
        "condition_type": "above",
        "threshold_max": -12,
        "alarm_text_pattern": "alta temperatura|temperatura alta|ambiente",
        "explanation_template": "Regra violada: Alta temperatura em congelados. O alarme ou leitura indica temperatura acima do limite esperado para equipamento de congelados.",
        "recommended_action_template": "Verificar porta, carga térmica, evaporador, degelo, vedação e condição do sistema de refrigeração. Confirmar leitura local antes de acionar manutenção.",
    },
    {
        "name": "Alta temperatura em resfriados",
        "description": "Identifica temperatura elevada em balcões, ilhas ou ambientes resfriados.",
        "scope_type": "equipment_type",
        "scope_value": "chilled",
        "priority": 20,
        "severity_when_triggered": "warning",
        "equipment_type": "chilled",
        "measurement_type": "temperature",
        "condition_type": "above",
        "threshold_max": 8,
        "alarm_text_pattern": "alta temperatura|temperatura alta|ambiente",
        "explanation_template": "Regra violada: Alta temperatura em resfriados. O ativo resfriado está acima da referência operacional configurada.",
        "recommended_action_template": "Verificar porta, exposição, carga térmica, ventilação, sensor e condição de refrigeração.",
    },
    {
        "name": "Faixa câmara fria resfriada",
        "description": "Valida câmara fria resfriada entre 0 C e 5 C.",
        "scope_type": "equipment_type",
        "scope_value": "cold_room_chilled",
        "priority": 25,
        "severity_when_triggered": "warning",
        "equipment_type": "cold_room_chilled",
        "measurement_type": "temperature",
        "condition_type": "outside_range",
        "threshold_min": 0,
        "threshold_max": 5,
        "alarm_text_pattern": "câmara fria|camara fria|resfriad",
        "explanation_template": "Regra violada: Câmara fria resfriada fora da faixa esperada de 0 C a 5 C.",
        "recommended_action_template": "Validar setpoint, sensor, porta, circulação de ar e condição do evaporador.",
    },
    {
        "name": "Faixa câmara congelada",
        "description": "Valida câmara ou equipamento congelado entre -25 C e -15 C.",
        "scope_type": "equipment_type",
        "scope_value": "cold_room_frozen",
        "priority": 15,
        "severity_when_triggered": "critical",
        "equipment_type": "cold_room_frozen",
        "measurement_type": "temperature",
        "condition_type": "outside_range",
        "threshold_min": -25,
        "threshold_max": -15,
        "alarm_text_pattern": "câmara|camara|congelad|cf|c.f.",
        "explanation_template": "Regra violada: Câmara congelada fora da faixa esperada de -25 C a -15 C.",
        "recommended_action_template": "Verificar porta, vedação, degelo, evaporador, carga térmica e leitura local.",
    },
    {
        "name": "Baixa temperatura operacional",
        "description": "Sinaliza leituras abaixo da faixa esperada e possível configuração incorreta.",
        "scope_type": "global",
        "priority": 55,
        "severity_when_triggered": "warning",
        "measurement_type": "temperature",
        "condition_type": "below",
        "threshold_min": -30,
        "alarm_text_pattern": "baixa temperatura|temperatura baixa",
        "explanation_template": "Regra violada: Baixa temperatura operacional. A leitura ou alarme aponta condição abaixo do limite de referência.",
        "recommended_action_template": "Verificar setpoint, sensor, controlador e risco de congelamento indevido.",
    },
    {
        "name": "Comunicação ou equipamento offline",
        "description": "Detecta ausência de comunicação ou status offline.",
        "scope_type": "alarm_group",
        "scope_value": "communication",
        "priority": 30,
        "severity_when_triggered": "warning",
        "measurement_type": "communication",
        "condition_type": "contains_text",
        "alarm_text_pattern": "offline|comunicação|sem comunicação|sinal|sem sinal",
        "explanation_template": "Regra violada: Comunicação ou equipamento offline. O alarme indica perda de comunicação ou indisponibilidade do controlador.",
        "recommended_action_template": "Verificar alimentação, rede, sinal, comunicação e disponibilidade do controlador.",
    },
    {
        "name": "Falha de compressor",
        "description": "Prioriza alarmes relacionados a compressor e proteção térmica.",
        "scope_type": "alarm_group",
        "scope_value": "compressor",
        "priority": 5,
        "severity_when_triggered": "critical",
        "measurement_type": "compressor",
        "condition_type": "contains_text",
        "alarm_text_pattern": "compressor|térmico compressor|termico compressor|falha int compressor|falha compressor",
        "explanation_template": "Regra violada: Falha de compressor. O texto do alarme indica risco em componente crítico do sistema de refrigeração.",
        "recommended_action_template": "Verificar compressor, proteção térmica, corrente, pressão e condição elétrica antes de liberar operação.",
    },
    {
        "name": "Baixa pressão ou glicol",
        "description": "Sinaliza baixa pressão, pressão de sucção ou circuito de glicol.",
        "scope_type": "alarm_group",
        "scope_value": "pressure_glycol",
        "priority": 8,
        "severity_when_triggered": "critical",
        "measurement_type": "pressure",
        "condition_type": "contains_text",
        "alarm_text_pattern": "baixa pressão|baixa pressao|pressão sucção|pressao succao|glicol",
        "explanation_template": "Regra violada: Baixa pressão ou glicol. O alarme aponta risco no circuito de refrigeração ou circulação.",
        "recommended_action_template": "Verificar circuito de refrigeração, fluido, bomba, válvulas e pressão de sucção.",
    },
    {
        "name": "MOP ou alta evaporação",
        "description": "Indica condição de evaporação elevada ou atuação MOP.",
        "scope_type": "alarm_group",
        "scope_value": "evaporation",
        "priority": 45,
        "severity_when_triggered": "warning",
        "measurement_type": "pressure",
        "condition_type": "contains_text",
        "alarm_text_pattern": "mop|alta temperatura de evaporação|alta temperatura de evaporacao",
        "explanation_template": "Regra violada: MOP ou alta evaporação. A operação pode estar fora do ponto de controle esperado.",
        "recommended_action_template": "Verificar válvula, carga térmica, evaporação e condição de operação.",
    },
    {
        "name": "Recorrência de evento",
        "description": "Prioriza equipamentos com repetição de ocorrências em janela curta.",
        "scope_type": "global",
        "priority": 12,
        "severity_when_triggered": "critical",
        "condition_type": "repeated_event",
        "recurrence_count": 3,
        "recurrence_window_minutes": 120,
        "explanation_template": "Regra violada: Recorrência de evento. O equipamento ou loja apresenta repetição de alarmes em janela operacional curta.",
        "recommended_action_template": "Priorizar análise técnica e acompanhar até estabilização da ocorrência.",
    },
    {
        "name": "Telemetria ausente",
        "description": "Sinaliza ausência de leitura suficiente sem confirmar falha de equipamento.",
        "scope_type": "global",
        "priority": 80,
        "severity_when_triggered": "info",
        "measurement_type": "communication",
        "condition_type": "missing_telemetry",
        "explanation_template": "Regra observada: Telemetria ausente. Não há leitura suficiente para confirmar condição operacional.",
        "recommended_action_template": "Validar comunicação do sensor antes de concluir falha no equipamento.",
    },
]
